### ISSUE TITLE
Return of NAN to report problem getting value

### ISSUE THREAD

**Issue by RobLewis** [adafruit/Adafruit-MAX31855-library#25]
My ESP8266 project reads a thermocouple and sends the value as JSON upon a HTTP request. This usually works fine but occasionally the returned JSON has `"nan"` in place of the temperature value. In the driver code I see that some error conditions cause a return of the constant `NAN`, but I can't find where this value is defined. My Arduino code that calls `.readCelsius()` expects a `double`. What is actually being returned, and how can I test for it?

**Comment by rswift** [comment]
There is a [test in `readCelsius()`](https://github.com/adafruit/Adafruit-MAX31855-library/blob/master/Adafruit_MAX31855.cpp#L96
) that checks bits `D0`, `D1` & `D2` which, [according to the data sheet](https://datasheets.maximintegrated.com/en/ds/MAX31855.pdf
) (and the comment in the code), indicate a problem. The specific bit (`D0`, `D1` and/or `D2`) will tell you exactly what your problem is, seemingly one of short circuit to Vcc, Ground or the thermocouple is open.

Google is your friend in terms of finding an easy way to test if the returned value `isnan()` or not :)

HTH - Robert...

**Comment by RobLewis** [comment]
Thanks. Retrying the read generally fixes the problem, so I don't see how it could realistically be a short or open circuit. I built the device myself and IMHO the possibility of intermittent connections is very low. 
I thought it might be some kind of race condition, so I added a loop that retries the read up to 10 times after a delay (starting at 50 ms and increasing). Haven't tested extensively but so far this seems to have satisfied my Android client. Do you know how long a read normally takes?

**Comment by rswift** [comment]
not suggesting your soldering skills are shoddy, just that `nan` is a result of those values, bad MAX31855 maybe? In terms of timing, I previously raised a PR for timing improvements, maybe useful? https://github.com/adafruit/Adafruit-MAX31855-library/pull/17

**Comment by vikingasia** [comment]
I think you'll find all K-types - regardless of dollars or vendor give you a '0' sometimes - near as I can tell, so you just have to find a way in the software to 'hide' that zero from being 'displayed' (or used in further calculations) - I have 11 k-type thermocouples, mostly from different vendors and they all give me a '0' sometimes

**Comment by caternuson** [comment]
Closing. NAN return is expected behavior for certain conditions.
