### ISSUE TITLE
warning: passing NULL to non-pointer argument

### ISSUE THREAD

**Issue by jenschr** [adafruit/Adafruit-MAX31855-library#41]
- Arduino board: Arduino Uno or Teensy 3.2

- Arduino IDE version (found in Arduino -> About Arduino menu): Arduino 1.8.13 or PlatformIO 2.1.0 (VSCode)

- List the steps to reproduce the problem below (if possible attach a sketch or
  copy the sketch code in too):

Download latest BusIO. Compile any Adafruit_MAX31855 sample project with Arduino IDE and Verbose output turned on in Preferences to see the following warning:

[code]In file included from /var/folders/t2/6m0f3ybs5rsbsdbfl_gg77fw0000gp/T/arduino_build_583631/sketch/Adafruit_MAX31855.cpp:36:0:
/var/folders/t2/6m0f3ybs5rsbsdbfl_gg77fw0000gp/T/arduino_build_583631/sketch/Adafruit_MAX31855.h:49:32: warning: passing NULL to non-pointer argument 1 of 'Adafruit_SPIDevice::Adafruit_SPIDevice(int8_t, uint32_t, BitOrder, uint8_t, SPIClass*)' [-Wconversion-null]
   Adafruit_SPIDevice spi_dev = NULL;[/code]

This is just a warning, but when using PlatformIO, you'll have to compile twice when touching any class using this. This is since VSCode will flag the warning in the "issues" tab. It disappears on the second compile, but users of other IDE's have also discovered this issue: https://forums.adafruit.com/viewtopic.php?f=25&t=162835 

The problem is that "spi_dev" is initialized to "NULL". From what I've learned, you don't initialise a complex data type in a header file and "NULL" is apparently not a valid value. Could it be that this should have been a Pointer instead, so it's allowed to be empty?

**Comment by AnHardt** [comment]
https://github.com/adafruit/Adafruit_MAX31865  (PT100) has exactly the same problem.

**Comment by ladyada** [comment]
@caternuson ahhh - wanna fix? it is bad news to NULL a non-pointer :) surprised it passed compile

**Comment by caternuson** [comment]
Hopefully fixed with #42

**Comment by jenschr** [comment]
Confirmed - great job!

**Comment by AnHardt** [comment]
The alternative fix would have been to do it like in most other Adafruit libraries using BusIO.
There i find a `Adafruit_SPIDevice *spi_dev = NULL;` instead of `Adafruit_SPIDevice spi_dev = NULL;`. A pointer instead of a object is initialized.
Then the spi_dev is created in the constructor with `spi_dev = new Adafruit_SPIDevice(_cs, ...` and  to access you have to use a `spi_dev->begin()` instead a `spi_dev.begin()`.

Creating the device on the heap normally also works without problems. But every `new` requires a `delete` and the standard destructor does not call that. You have to write your own destructor - what in most libraries is not done. This is not a real problem as long the class using the device is never destroyed, bit when - we have a memory leak.

For that i prefer the way i fixed it. 

Fixes for the [MAX31856](https://github.com/adafruit/Adafruit_MAX31856/blob/master/Adafruit_MAX31856.h#L137) and [MAX31865](https://github.com/adafruit/Adafruit_MAX31865/blob/master/Adafruit_MAX31865.h#L84) libraries will follow. Just have to find my modules for testing.
